# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('total_runs', models.IntegerField(default=0, null=True)),
                ('total_outs', models.IntegerField(default=0, null=True)),
                ('innings', models.IntegerField(default=0, null=True)),
                ('player_name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('batting_impact_list', models.CharField(max_length=500, null=True)),
                ('runs_in_matches', models.CharField(max_length=500, null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('batting_avg', models.FloatField(default=0, null=True)),
                ('caa', models.FloatField(default=0, null=True)),
                ('last_bat_impact', models.FloatField(default=0, null=True)),
                ('team_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
