# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashes', '0002_userplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplayers',
            name='search_target',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
