# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ashes', '0004_userplayers_articles_search_target'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500, null=True)),
                ('runs', models.CharField(max_length=10, null=True)),
                ('tournament', models.CharField(max_length=500, null=True)),
                ('balls_faced', models.CharField(max_length=10, null=True)),
                ('match_date', models.DateField()),
                ('fours', models.CharField(max_length=10, null=True)),
                ('six', models.CharField(max_length=10, null=True)),
                ('team_name', models.CharField(max_length=100, null=True)),
                ('opponent_team_name', models.CharField(max_length=100, null=True)),
                ('strike_rate', models.CharField(max_length=10, null=True)),
                ('match_status', models.CharField(max_length=500, null=True)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashes.PlayerStats')),
            ],
        ),
    ]
