# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashes', '0005_playermatchdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='player_match_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
