# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashes', '0006_playerstats_player_match_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='match_date',
            field=models.DateField(null=True),
        ),
    ]
