# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashes', '0009_auto_20160418_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='other_player',
            field=models.NullBooleanField(),
        ),
    ]
